import 'dart:convert';
import 'package:http/http.dart' as http; // You will need this for real API calls
import 'api_client.dart'; // Assuming this file handles the base URL
import '../models/company_model.dart';

class CompanyService {
  /// Tworzy nową firmę
  ///
  /// This method now only accepts 'name' and 'domain' because that is
  /// what the backend API expects for creation. The other fields (id, createdAt)
  /// are generated by the server.
  static Future<Company> createCompany({
    required String name,
    required String domain,
  }) async {
    // We don't create a local Company object here.
    // We create a simple Map that will be converted to the JSON body.
    final Map<String, String> body = {
      'name': name,
      'domain': domain,
    };

    final response = await ApiClient.post(
      'api/companies/', // Make sure this URL is correct
      body: jsonEncode(body),
      headers: {'Content-Type': 'application/json'},
    );

    if (response.statusCode == 201) {
      // The server responds with the full Company object, including the new id and createdAt
      return Company.fromJson(jsonDecode(response.body));
    } else {
      throw Exception('Błąd tworzenia firmy: ${response.body}');
    }
  }

  /// Pobiera listę wszystkich firm
  static Future<List<Company>> listCompanies() async {
    final response = await ApiClient.get('api/companies/list/');

    if (response.statusCode == 200) {
      final List<dynamic> data = jsonDecode(response.body);
      return data.map((json) => Company.fromJson(json)).toList();
    } else {
      throw Exception('Błąd pobierania firm: ${response.body}');
    }
  }

  /// Pobiera szczegóły jednej firmy
  ///
  /// Corrected the return type from 'ompany' to 'Company'.
  static Future<Company> getCompany(int id) async {
    final response = await ApiClient.get('api/companies/$id/');

    if (response.statusCode == 200) {
      return Company.fromJson(jsonDecode(response.body));
    } else {
      throw Exception('Błąd pobierania firmy: ${response.body}');
    }
  }
}