# Generated by Django 5.2.8 on 2026-03-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='badge_images/'),
        ),
    ]
