# Generated by Django 5.2.8 on 2026-05-25 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_badge_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    ooperations = [
    migrations.CreateModel(
        name='SectionProgress',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('completed', models.BooleanField(default=False)),
            ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseassignment')),
            ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
        ],
        options={
            'unique_together': {('assignment', 'section')},
        },
    ),
]