# Generated by Django 5.2.8 on 2025-12-16 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(help_text='The order of the section within the course (e.g., 1, 2, 3...)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('QUIZ', 'Quiz')], max_length=10)),
                ('order', models.PositiveIntegerField(help_text='The order of the block within the section')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL to the hosted image', null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL to the video (e.g., YouTube, Vimeo)', null=True)),
                ('quiz_title', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
