# Generated by Django 5.2.8 on 2026-06-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_description_thumbnail_duration'),
        ('core', '0004_add_course_completion_badge_and_sectionprogress'),
    ]

    operations = [
    ]
