# Generated by Django 5.2.8 on 2026-01-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accent_color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#2563EB', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(default='#1E40AF', max_length=7),
        ),
    ]
