# Generated by Django 5.2.8 on 2026-06-08 16:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_badge_workspace_badge_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='workspace',
        ),
        migrations.AddField(
            model_name='badge',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='core.course'),
        ),
        migrations.AddField(
            model_name='mentorrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorrating',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorrating',
            name='onboarding_task_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_ratings', to='core.onboardingtaskinstance'),
        ),
        migrations.AlterField(
            model_name='mentorrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddConstraint(
            model_name='mentorrating',
            constraint=models.UniqueConstraint(fields=('onboarding_task_instance',), name='uniq_onboarding_task_rating'),
        ),
    ]
