# Generated by Django 5.2.8 on 2026-01-13 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_accent_color_company_logo_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='template',
        ),
        migrations.RemoveField(
            model_name='onboarding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='onboardingtaskinstance',
            name='onboarding',
        ),
        migrations.RemoveField(
            model_name='onboardingtaskinstance',
            name='assigned_by_user',
        ),
        migrations.RemoveField(
            model_name='onboardingtaskinstance',
            name='assigned_to_user',
        ),
        migrations.RemoveField(
            model_name='onboardingtaskinstance',
            name='mentor_user',
        ),
        migrations.RemoveField(
            model_name='onboardingtaskinstance',
            name='template_task',
        ),
        migrations.RemoveField(
            model_name='onboardingtasktemplate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='onboardingtemplate',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='onboardingtemplate',
            name='workspace',
        ),
        migrations.AddField(
            model_name='badge',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='core.course'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste the URL of the badge image here', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=50, help_text='Minimum percentage required to pass (0-100)'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workspace'),
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, help_text='Content of the checkpoint/lesson', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='core.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MentorRating',
        ),
        migrations.DeleteModel(
            name='Onboarding',
        ),
        migrations.DeleteModel(
            name='OnboardingTaskInstance',
        ),
        migrations.DeleteModel(
            name='OnboardingTaskTemplate',
        ),
        migrations.DeleteModel(
            name='OnboardingTemplate',
        ),
    ]
