# Generated by Django 5.2.8 on 2026-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_badge_workspace_badge_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtaskinstance',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtaskinstance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtaskinstance',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onboardingtasktemplate',
            name='category',
            field=models.CharField(default='Techniczna', max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingtasktemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtasktemplate',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
