# Generated by Django 5.2.8 on 2026-06-16 22:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_badge_workspace_badge_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AddField(
            model_name='usercompany',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercompany',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('mentor', 'Mentor'), ('employee', 'Employee'), ('admin', 'Admin'), ('owner', 'Owner')], default='employee', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='usercompany',
            unique_together={('user', 'company')},
        ),
    ]
