# Generated by Django 5.2.8 on 2026-06-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_onboardingtaskinstance_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(default='Ogólne', max_length=100),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='star', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='rarity',
            field=models.CharField(default='common', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='xp_reward',
            field=models.IntegerField(default=100),
        ),
    ]
