# Generated by Django 5.2.8 on 2026-06-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_badge_category_badge_icon_badge_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='role',
            field=models.CharField(choices=[('employee', 'Pracownik'), ('hr', 'Dział HR'), ('admin', 'Administrator'), ('owner', 'Właściciel'), ('super_admin', 'Super Administrator')], default='employee', max_length=50),
        ),
    ]
